resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: showks-canvas-pr
  type: pull-request
  check_every: 600h
  webhook_token: ((github_webhook_token))
  source:
    repository: containerdaysjp/showks-canvas-USERNAME
    access_token: ((github_access_token))

- name: showks-canvas
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-canvas

jobs:
- name: test
  plan:
  - get: showks-canvas-pr
    trigger: true
    version: every
  - put: showks-canvas-pr
    params:
      path: showks-canvas-pr
      status: pending
  - get: showks-canvas
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: containerdaysjp/alpine-git-sed, tag: "latest"}
      inputs:
        - name: showks-canvas-pr
        - name: showks-canvas
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            diff -q -r -x ".git" showks-canvas showks-canvas-pr | grep -v "src/data/author.json"  | test $(wc -l) == 0
    on_failure:
      put: showks-canvas-pr
      params:
        path: showks-canvas-pr
        status: failure
    on_success:
      put: showks-canvas-pr
      params:
        path: showks-canvas-pr
        status: success

