resources:
- name: app
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-canvas-USERNAME
    branch: master

- name: app-staging
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-canvas-USERNAME
    branch: staging 

- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-concourse-pipelines
    branch: master

- name: k8s-manifests
  type: git
  source:
    uri: git@github.com:containerdaysjp/showks-manifests-prod.git
    branch: master
    private_key: ((github_key))

- name: container-image
  type: docker-image
  source:
    repository: gcr.io/ipc-containerdays/showks-canvas-USERNAME
    username: ((registry_user))
    password: ((registry_password))

jobs:
- name: push-image
  plan:
  - get: app-staging
  - get: app
    trigger: true
  - get: container-image
    params:
      tag_file: app-staging/.git/refs/heads/staging
      tag_prefix: stg-
      save: true
  - put: container-image
    params:
      load: container-image
      tag_file: app/.git/refs/heads/master
      tag_prefix: prod-
- name: update-manifest
  plan:
  - get: app
    trigger: true
    passed: ["push-image"]
  - get: k8s-manifests
  - get: concourse-pipelines
  - task: update-manifest
    file: concourse-pipelines/common/tasks/upload_manifest.yaml
    params:
      APP_NAME: showks-canvas-USERNAME
      TAG_PREFIX: prod-
      BRANCH: master
      USERID: USERNAME
      VHOST_DOMAIN: .prod.showks.containerdays.jp
      SERVICE_ACCOUNT: ((registry_password))
      PROJECT_NAME: ipc-containerdays

