platform: linux
image_resource:
  type: docker-image
  source:
    repository: containerdaysjp/docker
    tag: 18.06.1-ce-dind-git
inputs:
  - name: concourse-pipelines
  - name: app-master
outputs:
  - name: image.tar
run:
  path: concourse-pipelines/common/scripts/tagging.sh

