platform: linux
image_resource:
  type: docker-image
  source:
    repository: containerdaysjp/cloud-sdk-helm
inputs:
  - name: concourse-pipelines
  - name: app
  - name: k8s-manifests
outputs:
  - name: changed-k8s-manifests
run:
  path: concourse-pipelines/common/scripts/upload_manifest.sh

