resources:
- name: app
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showks-form.git"
- name: concourse-pipelines
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showks-concourse-pipelines.git"
- name: showks-canvas
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showks-canvas.git"
- name: showks-spinnaker-pipelines
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showks-spinnaker-pipelines.git"
- name: container-image
  type: docker-image
  source:
    repository: gcr.io/ipc-containerdays/showks-form
    username: ((registry_user))
    password: ((registry_password))
- name: k8s-manifests
  type: git
  source:
    uri: git@github.com:containerdaysjp/showks-manifests-stg.git
    branch: master
    private_key: ((github_stg_manifests_key))

jobs:
- name: unit-test
  plan:
  - get: app
    trigger: true
  - get: concourse-pipelines
    trigger: true
  - get: showks-canvas
    trigger: true
  - task: run-test
    file: concourse-pipelines/showks-form/tasks/unit-test.yml
- name: build-image
  plan:
  - get: app
    passed: ['unit-test']
    trigger: true
  - get: showks-canvas
    passed: ['unit-test']
    trigger: true
  - get: concourse-pipelines
    passed: ['unit-test']
    trigger: true
  - get: showks-spinnaker-pipelines
  - task: setup-assets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: containerdaysjp/alpine-git-sed
      inputs:
        - name: showks-canvas
        - name: concourse-pipelines
        - name: app
        - name: showks-spinnaker-pipelines
      outputs:
        - name: showks-form-output
      run:
        path: sh
        args:
        - -c
        - |
          cp -R app/* showks-form-output/
          find showks-form-output/
          cp -R showks-canvas showks-form-output/app/assets/
          cp -R showks-spinnaker-pipelines showks-form-output/app/assets/
          cp -R concourse-pipelines showks-form-output/app/assets/showks-concourse-pipelines
  - put: container-image
    params:
      build: showks-form-output
      build_args:
        RAILS_MASTER_KEY: ((masterkey))
      tag_file: app/.git/refs/heads/master
      tag_prefix: stg-
      tag_as_latest: true
- name: upload-manifest
  plan:
  - get: app
    trigger: true
    passed: ["build-image"]
  - get: concourse-pipelines
    passed: ['unit-test']
    trigger: true
  - get: showks-spinnaker-pipelines
  - get: k8s-manifests
  - task: update-manifest
    file: concourse-pipelines/common/tasks/upload_manifest.yaml
    params:
      APP_NAME: showks-form
      TAG_PREFIX: stg-
      BRANCH: master
      USERID: USERNAME
      NAME_SUFFIX: -temp
      VHOST_DOMAIN: .stg.showks.containerdays.jp
      SERVICE_ACCOUNT: ((registry_password))
      PROJECT_NAME: ipc-containerdays

