resources:
- name: showks-form
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showks-form.git"
- name: concourse-pipelines
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showks-concourse-pipelines.git"
    branch: jacopen
- name: showks-form-image
  type: docker-image
  source:
    repository: ((repository))
    username: ((username))
    password: ((password))

jobs:
- name: unit-test
  plan:
  - get: showks-form
    trigger: true
  - get: concourse-pipelines
  - task: run-test
    file: concourse-pipelines/showks-form/tasks/unit-test.yml
- name: build
  plan:
  - get: showks-form
    passed: ['unit-test']
    trigger: true
  - put: showks-form-image
    params:
      build: showks-form
