resources:
- name: app-master
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-aggregator
    branch: master

- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-concourse-pipelines
    branch: master

- name: showks-aggregator-image
  type: docker-image
  source:
    repository: containerdaysjp/showks-aggregator
    username: ((registry_user))
    password: ((registry_password))

jobs:
- name: master
  plan:
  - get: app-master
    trigger: true
  - get: concourse-pipelines
  - task: from-staging-image-to-master
    file: concourse-pipelines/common/tasks/tagging.yaml
    params:
      GITREPO: app-master/
      IMAGE_NAME: containerdaysjp/showks-aggregator

  - put: showks-aggregator-image
    params:
      load_file: outfile/image
      load_repository: containerdaysjp/showks-aggregator
      load_tag: latest
      tag_file: app-master/.git/refs/heads/master
      tag_prefix: prod-

  - task: update-manifest
    file: concourse-pipelines/common/tasks/update_manifest.yaml
    params:
      APP_NAME: showks-aggregator
      BRANCH: master
      GITHUB_KEY: ((github_key))

