resources:
- name: app
  type: git
  source:
    uri: https://github.com/cloudnativedaysjp/showks-aggregator
    branch: staging

- name: container-image
  type: docker-image
  source:
    repository: cloudnativedaysjp/showks-aggregator
    username: ((dockerhub_user))
    password: ((dockerhub_password))

- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/cloudnativedaysjp/showks-concourse-pipelines
    branch: master

- name: k8s-manifests
  type: git
  source:
    uri: git@github.com:cloudnativedaysjp/showks-manifests-stg.git
    branch: master
    private_key: ((github_stg_manifests_key))

jobs:
- name: build-image
  plan:
  - get: app
    trigger: true
  - get: concourse-pipelines
  - get: k8s-manifests
  - put: container-image
    params:
      build: app/
      tag_file: app/.git/refs/heads/staging
      tag_prefix: stg-
      tag_as_latest: true
- name: upload-manifest
  plan:
  - get: app
    trigger: true
    passed: ["build-image"]
  - get: k8s-manifests
  - get: concourse-pipelines
  - task: update-manifest
    file: concourse-pipelines/common/tasks/upload_manifest.yaml
    params:
      APP_NAME: showks-aggregator
      TAG_PREFIX: stg-
      BRANCH: staging
      USERID: USERNAME
      NAME_SUFFIX: -temp
      VHOST_DOMAIN: .stg.showks.containerdays.jp
      SERVICE_ACCOUNT: ((registry_password))
      PROJECT_NAME: ipc-containerdays

