resources:
- name: app
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-aggregator
    branch: staging

- name: showks-aggregator-image
  type: docker-image
  source:
    repository: containerdaysjp/showks-aggregator
    username: ((registry_user))
    password: ((registry_password))

- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-concourse-pipelines
    branch: master

jobs:
- name: staging
  plan:
  - get: app
    trigger: true
  - get: concourse-pipelines
  - put: showks-aggregator-image
    params:
      build: app/
      tag_file: app/.git/refs/heads/staging
      tag_prefix: stg-
      tag_as_latest: true

  - task: update-manifest
    file: concourse-pipelines/common/tasks/update_manifest.yaml
    params:
      APP_NAME: showks-aggregator
      BRANCH: staging
      GITHUB_KEY: ((github_key))
