resources:
- name: app-staging
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-aggregator
    branch: staging

- name: showks-aggregator-image
  type: docker-image
  source:
    repository: containerdaysjp/showks-aggregator
    username: ((registry_user))
    password: ((registry_password))

jobs:
- name: staging
  plan:
  - get: app-staging
    trigger: true

  - put: showks-aggregator-image
    params:
      build: app-staging/
      tag_file: app-staging/.git/refs/heads/staging
      tag_prefix: stg-
      tag_as_latest: true

  - task: update-manifest
    file: concourse-pipelines/common/tasks/update_manifest.yaml
    params:
      APP_NAME: showks-aggregator
      BRANCH: staging
      GITHUB_KEY: ((github_key))
