resources:
- name: showk-app
  type: git
  source:
    uri: "https://github.com/containerdaysjp/showk-app"

- name: showk-app-image
  type: docker-image
  source:
    repository: ((repository))
    username: ((username))
    password: ((password))

jobs:
- name: build
  plan:
  - get: showk-app
    trigger: true
  - put: showk-app-image
    params:
      build: showk-app
