resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: showks-portal-pr
  type: pull-request
  check_every: 1m
  webhook_token: ((github_webhook_token))
  source:
    repository: containerdaysjp/showks-portal
    access_token: ((github_access_token))

jobs:
- name: test
  plan:
  - get: showks-portal-pr
    trigger: true
    version: every
  - put: showks-portal-pr
    params:
      path: showks-portal-pr
      status: pending
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine/git, tag: "latest"}
      inputs:
        - name: showks-portal-pr
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            cd showks-portal-pr
            git config --global pager.log cat
            git log --graph --color --date-order -C -M --all --date=short --pretty=format:"<%h> %ad [%an] %Cgreen%d%Creset %s"
            sleep 3
            echo "unit test is here";
            exit 0;
    on_failure:
      put: showks-portal-pr
      params:
        path: showks-portal-pr
        status: failure
  - put: showks-portal-pr
    params:
      path: showks-portal-pr
      status: success

