# https://github.com/containerdaysjp/showks-concourse-pipelines/blob/master/showks-canvas-USERNAME/pr.yaml
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: containerdaysjp/pr

resources:
- name: showks-keycloak-user-operator-pr
  type: pull-request
  check_every: 1m
  source:
    repo: cloudnativedaysjp/showks-keycloak-user-operator
    access_token: ((access_token))
    private_key: ((private_key))

- name: showks-keycloak-user-operator
  type: git
  check_every: 1m
  source:
    uri: https://github.com/cloudnativedaysjp/showks-keycloak-user-operator
    branch: master

- name: docker-reg
  type: docker-image
  source:
    repository: cloudnativedaysjp/keycloak-user-operator
    username: ((dockerhub_username))
    password: ((dockerhub_password))

jobs:
- name: test
  plan:
  - get: showks-keycloak-user-operator-pr
    trigger: true
    version: every
  - put: showks-keycloak-user-operator-pr
    params:
      path: showks-keycloak-user-operator-pr
      status: pending
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.12"
      inputs:
        - name: showks-keycloak-user-operator-pr
          path: /go/src/github.com/cloudnativedaysjp/showks-keycloak-user-operator
      outputs:
        - name: messages
      run:
        path: /bin/bash
        args:
          - -xce
          - |
            GO111MODULE=off
            SRCPATH=$PWD/go/src/github.com/cloudnativedaysjp/showks-keycloak-user-operator
            GOPATH=$PWD/go
            cd $SRCPATH
            wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.8/kubebuilder_1.0.8_linux_amd64.tar.gz
            tar xvzf kubebuilder_1.0.8_linux_amd64.tar.gz
            export TEST_ASSET_KUBECTL=$SRCPATH/kubebuilder_1.0.8_linux_amd64/bin/kubectl
            export TEST_ASSET_KUBE_APISERVER=$SRCPATH/kubebuilder_1.0.8_linux_amd64/bin/kube-apiserver
            export TEST_ASSET_ETCD=$SRCPATH/kubebuilder_1.0.8_linux_amd64/bin/etcd
            env
            make test
    on_failure:
      put: showks-keycloak-user-operator-pr
      params:
        path: showks-keycloak-user-operator-pr
        status: failure
    on_success:
      put: showks-keycloak-user-operator-pr
      params:
        path: showks-keycloak-user-operator-pr
        status: success

- name: deploy
  plan:
  - get: showks-keycloak-user-operator
    trigger: true
    version: every
  - put: docker-reg
    params:
      build: ./showks-keycloak-user-operator

