platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3.3
inputs:
  - name: showks-form
  - name: concourse-pipelines
outputs:
  - name: outfile
run:
  path: concourse-pipelines/showks-form/tasks/unit-test.sh
  args: [
    --input-dir, showks-form
  ]
