resources:
- name: app
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-portal-backend
    branch: staging

- name: container-image
  type: docker-image
  source:
    repository: containerdaysjp/showks-portal-backend
    username: ((registry_user))
    password: ((registry_password))

- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-concourse-pipelines
    branch: master

- name: k8s-manifests
  type: git
  source:
    uri: git@github.com:containerdaysjp/showks-manifests-stg.git
    branch: master
    private_key: ((github_stg_manifests_key))

jobs:
- name: staging
  plan:
  - get: app
    trigger: true
  - get: concourse-pipelines
  - get: k8s-manifests
  - put: container-image
    params:
      build: app/
      tag_file: app/.git/refs/heads/staging
      tag_prefix: stg-
      tag_as_latest: true
  - task: update-manifest
    file: concourse-pipelines/common/tasks/update_manifest.yaml
    params:
      APP_NAME: showks-portal-backend
      TAG_PREFIX: stg-
      BRANCH: staging
      NAME_SUFFIX: -temp
      VHOST_DOMAIN: .stg.showks.containerdays.jp
  - put: k8s-manifests
    params:
      repository: changed-k8s-manifests
